### ISSUE TITLE
dealing with token expiry

### ISSUE THREAD

**Issue by Dieterbe** [feedhenry/openstack-storage#7]
maybe it's just me, but i didn't see anything to deal with tokens expiring, and re-calling the auth function to get new tokens.
OpenStackStorage has a self.authFn but never calls it.

Am I, as an implementer of this library responsible to deal with token expiry-getting new tokens everywhere? or shouldn't the library deal with this transparently?

**Comment by camilamacedo86** [comment]
Closing issue since this project is deprecated and not so long keep maintained.
